name: lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Linting
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
    - name: Install dependencies
      run: |
        sudo apt-get install libsqlite3-dev
        bundle install
    - name: Run tests
      run: bundle exec rubocop --config=./.rubocop.yml --parallel
