name: tests

on: [push]

jobs:
  unit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [ '3.1.x', '3.2.x' ]
        # gemfile: [ 'Gemfile', 'gemfiles/rails_51.gemfile', 'gemfiles/rails_52.gemfile' ]
        gemfile: [ 'Gemfile' ]
    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby ${{ matrix.ruby }}
      uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Install dependencies
      run: |
        sudo apt-get install libsqlite3-dev -y
        gem install bundler --no-document
        BUNDLE_GEMFILE=${{ matrix.gemfile }} bundle install --with=test
    - name: Run tests
      run: BUNDLE_GEMFILE=${{ matrix.gemfile }} bundle exec rails test
